services:
  askme:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MANAGEMENT_CONNECTION_STRING=management:8080
    depends_on:
      - ollama
      - management
    networks:
      - ollama-net
      - management-net

  management:
    build: ./management
    environment:
      - ADMIN_PW=${ADMIN_PW}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OLLAMA_CONNECTION_STRING=ollama:11434 
    volumes:
      - management-data:/management-data
    ports:
      - "8080:8080"
    networks:
      - management-net

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ollama-net

volumes:
  ollama-data:
  management-data:

networks:
  management-net:
    driver: bridge
  ollama-net:
    driver: bridge