services:
  askme:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_CONNECTION_STRING=ollama:11434  # Point to ollama service
    depends_on:
      - ollama
    networks:
      - ollama-net

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ollama-net

volumes:
  ollama-data:

networks:
  ollama-net:
    driver: bridge