services:
  askme:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_CONNECTION_STRING=ollama:11434 
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ADMIN_PW=${ADMIN_PW}
    depends_on:
      - ollama
    networks:
      - ollama-net

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ollama-net

volumes:
  ollama-data:

networks:
  ollama-net:
    driver: bridge